auth:
  strategy: "anonymous"

deployment:
  ingress:
    enabled: false

external_services:
  custom_dashboards:
    enabled: true
  istio:
    root_namespace: "istio-system"
  prometheus:
    enabled: true
    url: http://prometheus-stack-kube-prom-prometheus.prometheus-stack:9090
