apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-public # Creates a Public ingress ELB
  namespace: istio-ingress
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    hostname: "*.${route53_domain}"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: service # only traffic destined for Services will be proxied through waypoint.
  name: waypoint # Deploys waypoint proxy to process L7's istio network features
  namespace: istio-system
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
    allowedRoutes:
      namespaces:
        from: Selector # 'All' to allow from any namespaces
        selector:
          matchLabels:
            kubernetes.io/metadata.name: app # allow resources in a namespace to use this gateway