## kubectl create namespace istio-ingress
#
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: app
#  labels:
#    istio.io/dataplane-mode: ambient # To add applications or namespaces to the mesh in ambient mode
#    istio.io/use-waypoint: waypoint # must match the waypoint's Gateway 'name'. By default, matches waypoint from the same namespace
#    #istio.io/use-waypoint-namespace: istio-system # allow apps Pods to access the waypoint from the istio-system namespace
#    istio.io/use-waypoint-namespace: app # allow apps Pods to access the waypoint from the istio-system namespace
#  annotations:
#    networking.istio.io/traffic-distribution: PreferSameZone # Prioritize endpoints by proximity: network, region, zone, then subzone. Traffic goes to the closest healthy endpoints first.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: http
  namespace: app
---
apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: app
  labels:
    app: http
    service: http
  annotations:
    networking.istio.io/traffic-distribution: PreferSameZone 
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http
      version: v1
  template:
    metadata:
      labels:
        app: http
        version: v1
        # istio.io/dataplane-mode: ambient # To add applications or namespaces to the mesh in ambient mode
    spec:
      serviceAccountName: http
      containers:
      - image: httpd:2.4.67
        imagePullPolicy: IfNotPresent
        name: http
        ports:
        - containerPort: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http
  namespace: app
spec:
  parentRefs:
  - name: gateway-public
    namespace: istio-ingress
    sectionName: https # precisa fazer bind no 'https' pois 'http' vai fazer apenas redirect para o https.
  hostnames: ["http.ricardoxyz.website"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: http
      port: 8000
---
apiVersion: security.istio.io/v1 
kind: AuthorizationPolicy # Enforce Layer 7 authorization policy - allow or deny which services can communicate with http pods
metadata:
  name: http-waypoint
  namespace: app
spec: # https://ambientmesh.io/docs/security/waypoint-authz/
  targetRefs: # targetRefs is for L7 waypoint policies
  - kind: Service # Can be a Service, Waypoint or WaypointClass
    name: http
  action: ALLOW
  rules:
    - from:
      - source:
          principals:
          - cluster.local/ns/app/sa/alpine # only allow L7 traffic from this service account. Others will get "RBAC: access denied"
      to:
      - operation:
          methods: ["GET"] # Enforce Layer 7 authorization policy. Requires waypoint proxy install.
---
apiVersion: security.istio.io/v1 
kind: AuthorizationPolicy # Enforce Layer 4 authorization policy - allow or deny which services can communicate with http pods
metadata:
  name: http-ztunnel
  namespace: app
spec: # https://ambientmesh.io/docs/security/waypoint-authz/
  selector: # selector is for ztunnel L4 policies
    matchLabels:
      app: http # select this service
  action: ALLOW
  rules:
    - from:
      - source:
          principals: # traffic not defined will receive: "upstream connect error or disconnect/reset before headers. reset reason: connection termination"
          - cluster.local/ns/app/sa/waypoint # allow all L4 traffic from this waypoint. "Waypoint proxies do not impersonate the identity of the source workload. Once you have introduced a waypoint to the traffic path, the destination ztunnel will see traffic with the waypoint’s identity, not the source identity.". "Even if you only wish to enforce policy against L4 attributes, if you are dependent on the source identity, you should attach your policy to your waypoint proxy."
          - cluster.local/ns/istio-ingress/sa/gateway-public-istio # allow all L4 traffic from ingress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alpine
  namespace: app
---
apiVersion: v1
kind: Service
metadata:
  name: alpine
  namespace: app
  labels:
    app: alpine
    service: alpine
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
      version: v1
  template:
    metadata:
      labels:
        app: alpine
        version: v1
    spec:
      serviceAccountName: alpine
      containers:
      - image: alpine:3.23.4
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "apk add curl && watch -n 1 curl http://http:8000"] # curl http://http.app:8000
        name: alpine
        ports:
        - containerPort: 80
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http
  namespace: app # must be in the same namespace as target object
  annotations:
    autoscaling.keda.sh/paused: "false" # false: disable scale in AND out. 
    #autoscaling.keda.sh/paused-replicas: "0" # will scale your current workload to specified amount of replicas and pause autoscaling. You can set the value of replicas for an object to be paused to any arbitrary number.
    #autoscaling.keda.sh/force-activation: "false" # true: KEDA will treat all configured scalers as active. If the scalers were previously not active, KEDA will scale the service up from 0.
spec:
  scaleTargetRef:
    name: http
  minReplicaCount: 1
  maxReplicaCount: 3
  pollingInterval: 60
  cooldownPeriod: 180
  initialCooldownPeriod: 30
  advanced:
    restoreToOriginalReplicaCount: true # when scaleobject deleted
  triggers:
    - type: prometheus
      metadata:
        useCachedMetrics: true #  Enables caching of metric values during polling interval. Can significantly reduce the load on the scaler service.
        serverAddress: http://prometheus-stack-kube-prom-prometheus.prometheus-stack:9090
        activationThreshold: '1' # for 'Activation' phase. Defines when the scaler is active or not and scales FROM/TO 0 based on it. # Scales from 0 only when requests exceed X.
        threshold: '3' # for "Scaling" phase. Defines the target value to scale the workload FROM 1 TO N instances and vice versa.
        query: sum(rate(istio_requests_total{destination_workload="http"}[90s]))

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alpine-outside
  namespace: prometheus-stack
---
apiVersion: v1
kind: Service
metadata:
  name: alpine-outside
  namespace: prometheus-stack
  labels:
    app: alpine
    service: alpine
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-outside
  namespace: prometheus-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
      version: v1
  template:
    metadata:
      labels:
        app: alpine
        version: v1
    spec:
      serviceAccountName: alpine-outside
      containers:
      - image: alpine:3.23.4
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "apk add curl && watch -n 1 curl http://http.app:8000"] # curl http://http.app:8000
        name: alpine
        ports:
        - containerPort: 80
---